frontend/src/actions/index.js
frontend/src/reducers/index.js

The bug was caused by code I left in the reducer that required actions I hadn't made yet, and so returning a 'not defined' react error message. 
I made the actions that needed to be defined, and now the front end successfully starts (locally at least).

Bug fix between actions and router

---

Router/Class/createClassRouter.js
Router/Class/deleteClassRouter.js
Router/Class/findClassesRouter.js
Router/Class/updateClassRouter.js
Router/User/deleteUserRouter.js
Router/User/findUsersRouter.js
Router/User/loginUserRouter.js
Router/User/registerUserRouter.js
Router/User/updateUserRouter.js
frontend/package-lock.json
frontend/src/components/classList/index.css
frontend/src/components/classList/index.js
server.js

Add Link to class/create
Update Model Folder Structure
Added some styling to ClassList
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- …

Minor Additions

---

Router/User/findUsersRouter.js
Router/User/registerUserRouter.js
Router/User/updateUserRouter.js
Schemas/User.js
frontend/package-lock.json
frontend/package.json
frontend/src/App.js
frontend/src/actions/index.js
frontend/src/components/landing/index.js
frontend/src/components/login/index.js
frontend/src/navigation/LogOut/index.js
frontend/src/reducers/index.js

- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] My code has been reviewed by at least one peer
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have …

User Signup and Login almost Done

---

frontend/src/components/landing/index.js

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] My code has been reviewed by at least one peer
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made …

Fixes Redirect from Signup to Login

---

Procfile
package.json

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] My code has been reviewed by at least one peer
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made …

Deployment Troubleshooting

---

frontend/src/components/classList/ClassForm.js
frontend/src/components/classList/index.css
frontend/src/components/classList/index.js

Fixing styling bugs

---

README.md

Adding Docs

---

frontend/src/components/setting/setting.css
frontend/src/components/setup/setup.css

updated mobile design for settings page.

Stone Chris | Front End

---

backend/server.js
frontend/src/actions/index.js
frontend/src/components/classList/ClassForm.js

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] My code has been reviewed by at least one peer
- [ x ] I have commented my code, …

Adds student list compiler to ClassForm

---

backend/Router/Class/addtoClassRouter.js
backend/Router/Class/createClassRouter.js
backend/Schemas/Student.js
frontend/src/actions/index.js
frontend/src/components/classList/ClassForm.js

Add Class and Students Working Properly

---

frontend/package-lock.json
frontend/src/actions/index.js

filter added to GETCLASSES

---

frontend/package-lock.json
frontend/src/components/classList/index.js
frontend/src/reducers/index.js

ClassList mapping classes, linking to correct ID

---

README.md
backend/Router/User/loginUserRouter.js
backend/Router/User/updateUserRouter.js
backend/Schemas/Class.js
backend/Schemas/User.js
backend/package-lock.json
frontend/package-lock.json
frontend/src/actions/index.js
frontend/src/components/classList/ClassForm.js
frontend/src/components/landing/index.js
frontend/src/components/setup/index.js

README Navigation Guide Added
Signup button added to top of Landing Page
Settings editUser WIP

README Navigation Guide Added

---

frontend/package-lock.json
frontend/src/App.js
frontend/src/components/classList/index.js
frontend/src/components/magicRandomizer/index.js
package-lock.json

Randomizer working with correct classes

---

frontend/src/actions/index.js

switch to Heroku URL

---

backend/server.js

New Heroku Database added

---

frontend/src/actions/index.js
frontend/src/components/classList/ClassForm.js
frontend/src/components/classList/form.css
frontend/src/components/classList/index.css
frontend/src/components/classList/index.js
frontend/src/components/magicRandomizer/index.js
frontend/src/components/magicRandomizer/magicRandomizer.css
frontend/src/navigation/SideBar/index.css

Participation, delete student from Classlist, Randomizer mode Toggle

---

backend/Router/User/loginUserRouter.js
backend/Router/User/registerUserRouter.js
backend/Router/User/updateUserRouter.js
backend/Schemas/User.js
backend/server.js
frontend/package-lock.json
frontend/package.json
frontend/public/index.html
frontend/src/App.css
frontend/src/App.js
frontend/src/actions/index.js
frontend/src/components/billing/billing.css
frontend/src/components/classList/ClassForm.js
frontend/src/components/classList/form.css
frontend/src/components/classList/index.css
frontend/src/components/classList/index.js
frontend/src/components/landing/index.js
frontend/src/components/landing/landing.css
frontend/src/components/magicRandomizer/index.js
frontend/src/components/magicRandomizer/magicRandomizer.css
frontend/src/components/setup/index.js
frontend/src/components/setup/setup.css
frontend/src/index.css
frontend/src/index.js
frontend/src/reducers/index.js

Multiple Commits - Walter S Woodward

---

frontend/src/components/classList/ClassForm.js
frontend/src/components/classList/index.css
frontend/src/components/magicRandomizer/index.js
frontend/src/components/magicRandomizer/magicRandomizer.css

Randomizer Style / Bug Fixes

---

frontend/src/components/classList/ClassForm.js

Fixes removeStudent in ClassForm

Fixes removeStudent in ClassForm

---

backend/Schemas/Class.js
frontend/src/actions/index.js
frontend/src/components/classList/ClassForm.js
frontend/src/components/classList/form.css
frontend/src/components/landing/index.js
frontend/src/components/landing/landing.css
frontend/src/components/magicRandomizer/index.js
frontend/src/components/magicRandomizer/magicRandomizer.css

Style tweaking

---

backend/Router/Class/updateClassRouter.js
backend/package-lock.json
frontend/src/App.js
frontend/src/actions/index.js
frontend/src/components/classList/ClassForm.js
frontend/src/components/classList/editForm.js
frontend/src/components/classList/index.js
frontend/src/components/magicRandomizer/index.js
frontend/src/reducers/index.js

- X ] New feature (non-breaking change which adds functionality)

Edit functionality

---

backend/Router/Class/updateClassRouter.js
backend/Router/User/stripepaymentUserRouter.js
backend/Router/User/updateUserRouter.js
frontend/src/actions/index.js
frontend/src/components/billing/checkoutForm/index.js
frontend/src/components/classList/index.js
frontend/src/components/magicRandomizer/index.js
frontend/src/components/magicRandomizer/magicRandomizer.css
frontend/src/reducers/index.js

Fixing Bugs and Connecting Billing to Backend WIP

---

backend/Router/Class/updateClassRouter.js
frontend/src/actions/index.js
frontend/src/components/classList/ClassForm.js
frontend/src/components/classList/editForm.js
frontend/src/reducers/index.js

Fixes updateClassRouter so that it returns updated class
Fixes editForm so that if allMode or trackMode were activated, then their respective check boxes will be activated
Adds users and participation fields in editClass in actions as they were returning null after being edited

Bug fixes after last few merges

---

backend/package-lock.json
backend/server.js
frontend/package-lock.json
frontend/src/actions/index.js
frontend/src/components/landing/index.js
frontend/src/components/magicRandomizer/index.js

Now clears localStorage at Landing Page

---

backend/package-lock.json
backend/server.js
frontend/package-lock.json
frontend/src/actions/index.js
frontend/src/components/classList/editForm.js
frontend/src/components/magicRandomizer/index.js

Logically, the new feature works. The styling is broken.

Alternate randomizer

---

frontend/src/components/classList/editForm.js
frontend/src/components/magicRandomizer/index.js

Edit Temp Route Fix, Conditional Randomize CSS Distrobution

---

backend/package-lock.json
frontend/package-lock.json
frontend/package.json
frontend/src/components/magicRandomizer/index.js

Fixes bugs from Graph feature merge

---

frontend/src/components/magicRandomizer/index.js

Fixes some faulty logic related to when All Go is OFF and Tracker is ON

---

frontend/src/actions/index.js
frontend/src/components/classList/ClassForm.js
frontend/src/components/classList/editForm.js
frontend/src/components/classList/index.css
frontend/src/components/classList/index.js
frontend/src/components/landing/index.js
frontend/src/components/magicRandomizer/index.js
frontend/src/components/magicRandomizer/magicRandomizer.css
frontend/src/index.js
frontend/src/reducers/index.js

Adds On Deck Feature to App
Also refactors ClassList, but there shouldn't be any difference in the render there

Adds On Deck Feature

---

frontend/src/components/classList/ClassForm.js
frontend/src/components/classList/form.css
frontend/src/components/magicRandomizer/TrackNoAll.css
frontend/src/components/magicRandomizer/index.js
frontend/src/components/magicRandomizer/magicRandomizer.css

Class Form CSS Almost Perfect WIP

---

frontend/src/components/magicRandomizer/NoTrackNoAll.css
frontend/src/components/magicRandomizer/index.js
frontend/src/components/magicRandomizer/magicRandomizer.css

Working on NoTrackNoAll CSS

---

backend/package-lock.json
frontend/package-lock.json
frontend/src/App.css
frontend/src/components/magicRandomizer/TrackAll.css
frontend/src/components/magicRandomizer/index.js
frontend/src/components/magicRandomizer/magicRandomizer.css

Checked responsiveness on multiple monitors and with Chrome inspection.

TrackAll version complete except graph

---

frontend/public/index.html
frontend/src/components/magicRandomizer/NoTrackAll.css
frontend/src/components/magicRandomizer/NoTrackNoAll.css
frontend/src/components/magicRandomizer/TrackAll.css
frontend/src/components/magicRandomizer/TrackNoAll.css
frontend/src/components/magicRandomizer/index.js
frontend/src/components/magicRandomizer/magicRandomizer.css
frontend/src/index.css

Randomizer and LineGraph CSS
